// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace guvenport.Models;

public partial class AccidentReportStaff
{
    public int IdAccident { get; set; }

    public int IdStaff { get; set; }
    [JsonIgnore]
    public virtual Accident IdAccidentNavigation { get; set; }
    [JsonIgnore]
    public virtual Staff IdStaffNavigation { get; set; }
}