// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace guvenport.Models;

public partial class Accident
{
    public int Id { get; set; }

    public DateOnly? AccDate { get; set; }

    public TimeOnly? AccTime { get; set; }

    public bool? Fatality { get; set; }

    public bool? Injury { get; set; }

    public bool? PropertyDamage { get; set; }

    public bool? NearMiss { get; set; }

    public string StoryOfAccident { get; set; }

    public int? IdWorkplace { get; set; }

    public DateOnly? SgkInfoDate { get; set; }

    public bool? SgkInfoCheck { get; set; }

    public virtual Workplace IdWorkplaceNavigation { get; set; }

    public virtual ICollection<Contract> IdContract { get; set; } = new List<Contract>();

    public virtual ICollection<Staff> IdStaff { get; set; } = new List<Staff>();
}