// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace guvenport.Models;

public partial class ContractAccident
{
    public int IdContract { get; set; }

    public int IdAccident { get; set; }
    [JsonIgnore]
    public virtual Accident IdAccidentNavigation { get; set; }
    [JsonIgnore]
    public virtual Contract IdContractNavigation { get; set; }
}