// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace guvenport.Models;

public partial class Staff
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Ssn { get; set; }

    public string Password { get; set; }

    public string Mail { get; set; }

    public DateOnly? Dob { get; set; }

    public bool? Active { get; set; }

    public virtual Doctor Doctor { get; set; }

    public virtual ICollection<Office> Office { get; set; } = new List<Office>();

    public virtual ICollection<Accident> IdAccident { get; set; } = new List<Accident>();

    public virtual ICollection<Office> IdOffice { get; set; } = new List<Office>();

    public virtual ICollection<Workplace> IdWorkplace { get; set; } = new List<Workplace>();
}