// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace guvenport.Models;

public partial class Workplace
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string SocialSecurityNumber { get; set; }

    public bool? Active { get; set; }

    public string Adress { get; set; }

    public int? IdOffice { get; set; }

    public int? HazardLevel { get; set; }

    public virtual ICollection<Accident> Accident { get; set; } = new List<Accident>();

    public virtual ICollection<Contract> Contract { get; set; } = new List<Contract>();

    public virtual Office IdOfficeNavigation { get; set; }

    public virtual ICollection<Staff> IdStaff { get; set; } = new List<Staff>();
}